### ISSUE TITLE
Random missreading of parameter

### ISSUE THREAD

**Issue by jricardo27** [infoxchange/docker-forklift#25]
Randomly, forklift appears to miss-read my parameters:

> forklift my-image sshd
> usage: forklift [options]
> forklift: error: argument --services: invalid choice: 'my-image' (choose from 'proxy', 'email', 'elasticsearch', 'syslog', 'memcache', 'postgres', 'postgis')
> 
> forklift my-image sshd
> ssh app@localhost -p 49182 -A

My forklift.yaml

```
services:
 - syslog
 - postgis
 - elasticsearch
 - memcache

serve_port: 8002

storage: /tmp/my_storage

postgis:
    host: my_db_server
    port: 5433
    user: my_user
    password: my_pwd
    name: my_db

elasticsearch:
    urls: http://my-elastic-01:9200|http://my-elastic-02:9200|http://my-elastic-03:9200
    index_name: my_index_name

memcache:
    host: my-memcache-01:11211
    key_prefix: my_key_prefix

environment:
    ENVIRONMENT: dev
    EMAIL_HOST: email
    DB_DEFAULT_URL: postgis://my_user:my_pwd@my_db_server:5433/my_db
    SITE_DOMAIN: my_site
    SITE_PROTOCOL: http
```
